name: Fetch Economic Data

on:
  schedule:
    - cron: '0 0 1 * *'  # Monthly on the 1st
  workflow_dispatch:      # Manual trigger option

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run fetch script
        run: python Source/fetch_data.py

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          git add Data/economic_data.csv
          if git diff --cached --quiet; then
            echo "📭 No changes to commit"
          else
            git commit -m "📈 Update economic data"
            git push
          fi
